### ISSUE TITLE
Default svg style

### ISSUE THREAD

**Issue by hugolpz** [jerosoler/waveform-path#8]
Hello @jerosoler ,

A feature suggestion. I would like to replicate your elegant rainbow color in a programmatic way but it proves difficult to add it after generation. 

It could be interesting to have a way to define the default style for all waves to come.

```
var options = { 
defs : `
              <defs>
                  <linearGradient id="lgrad" x1="0%" y1="50%" x2="100%" y2="50%" >
                      <stop offset="0%" style="stop-color:rgb(0,255,10);stop-opacity:1.00" />
                      <stop offset="25%" style="stop-color:rgb(0,188,212);stop-opacity:0.70" />
                      <stop offset="50%" style="stop-color:rgb(238,130,238);stop-opacity:1.00" />
                      <stop offset="75%" style="stop-color:rgb(103,58,183);stop-opacity:0.70" />
                      <stop offset="100%" style="stop-color:rgb(233,30,99);stop-opacity:1.00" />
                  </linearGradient>
              </defs>`,
id:"lgrad"
};
```

I battled for a while but I couldn't make it work out : [before](https://jsfiddle.net/hugolpz/vre7hgto/15/) vs [after](https://jsfiddle.net/hugolpz/vre7hgto/18/)

**Comment by jerosoler** [comment]
For css I just tried two methods.
They work with the library, the problem is with the web component.

We can edit the color of the path through CSS. For example:
```css
wave-audio-path-player::part(path2) {
    stroke-width: 3px;
// Method 1
    stroke: url(/test.svg#lgrad); 
// Method 2
    stroke: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg"><linearGradient id="lgrad" x1="0%" y1="50%" x2="100%" y2="50%"><stop offset="0%" style="stop-color:rgb(0,255,10);stop-opacity:1.00"></stop><stop offset="25%" style="stop-color:rgb(0,188,212);stop-opacity:0.70"></stop><stop offset="50%" style="stop-color:rgb(238,130,238);stop-opacity:1.00"></stop><stop offset="75%" style="stop-color:rgb(103,58,183);stop-opacity:0.70"></stop><stop offset="100%" style="stop-color:rgb(233,30,99);stop-opacity:1.00"></stop></linearGradient></svg>#lgrad');
}
```

**test.svg file**
```svg
<svg id="example1" height="140px" width="800px" xmlns='http://www.w3.org/2000/svg' >
    <defs>
    <linearGradient id="lgrad" x1="0%" y1="50%" x2="100%" y2="50%">
        <stop offset="0%" style="stop-color:rgb(0,255,10);stop-opacity:1.00"></stop>
        <stop offset="25%" style="stop-color:rgb(0,188,212);stop-opacity:0.70"></stop>
        <stop offset="50%" style="stop-color:rgb(238,130,238);stop-opacity:1.00"></stop>
        <stop offset="75%" style="stop-color:rgb(103,58,183);stop-opacity:0.70"></stop>
        <stop offset="100%" style="stop-color:rgb(233,30,99);stop-opacity:1.00"></stop>
    </linearGradient>
    </defs>
</svg>
```

These two methods work in "Firefox" in Chrome, they are not shown to me.
